/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import business.Car;
import business.Manufacturer;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author shaojinnan
 */
public class CreateJPanel extends javax.swing.JPanel {
    
    private boolean isCreate;
    private Car car;
    private List<Car>cars;
    private List<Manufacturer>manufacturers;
    
    public CreateJPanel(List<Car>cars, List<Manufacturer> manufacturers) {
        this(null, cars, manufacturers);
    }

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(Car Car, List<Car>cars, List<Manufacturer> manufacturers) {
        initComponents();
        
        this.cars = cars;
        this.manufacturers = manufacturers;
        
        isCreate = car == null;
        if(isCreate){
            this.car = new Car();
            this.title.setText("Create Car");
            this.confirmButton.setText("Create");
        } else {
            this.car = car;
            this.title.setText("Update Car");
            this.confirmButton.setText("Update");
        }       
        
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(Manufacturer item : manufacturers) {
            model.addElement(item);
        }
        
        manufacturerCombobox.setModel(model);
        
        availableCheckbox.setSelected(this.car.isAvailable());
        manufacturerCombobox.setSelectedItem(this.car.getManufacturer());
        manufacturerTimeField.setText(this.car.getManufacturingTime() + "");
        seatsField.setValue(this.car.getSeats());
        serialNumberField.setText(this.car.getSerialNumber());
        modelNumberField.setText(this.car.getModelNumber());
        cityField.setText(this.car.getCity());
        mceDateField.setText(new SimpleDateFormat("yyyy-M-d").format(this.car.getExpired()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        availableCheckbox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        manufacturerCombobox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        manufacturerTimeField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        seatsField = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        serialNumberField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        modelNumberField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mceDateField = new javax.swing.JFormattedTextField();
        confirmButton = new javax.swing.JButton();

        title.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        title.setText("Create Car");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("IsAvailable:");

        availableCheckbox.setText(" ");
        availableCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableCheckboxActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Manufacturer:");

        manufacturerCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturerComboboxActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Manufacturer Time:");

        manufacturerTimeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Seats:");

        seatsField.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Serial Number:");

        serialNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumberFieldActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Model Number:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("CIty:");

        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Maintenance Cert Expired Date:");

        mceDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        mceDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mceDateFieldActionPerformed(evt);
            }
        });

        confirmButton.setText("Create");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cityField)
                            .addComponent(modelNumberField)
                            .addComponent(serialNumberField)
                            .addComponent(availableCheckbox)
                            .addComponent(manufacturerCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manufacturerTimeField)
                            .addComponent(mceDateField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(seatsField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addGap(0, 67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availableCheckbox)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(manufacturerCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(manufacturerTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(seatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(serialNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mceDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(confirmButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void availableCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableCheckboxActionPerformed

    private void manufacturerComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturerComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturerComboboxActionPerformed

    private void serialNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumberFieldActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        // 校验
        Manufacturer manu = (Manufacturer) manufacturerCombobox.getSelectedItem();
        if(manu == null) {
            JOptionPane.showMessageDialog(null, "Please select manufacturer!");
            return;
        }
        
        
        int year;
        try {
            Date date = new SimpleDateFormat("yyyy").parse(manufacturerTimeField.getText());
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(date);
            year = calendar.get(Calendar.YEAR);
        } catch (ParseException ex) {
          JOptionPane.showMessageDialog(null, "Please input year with right format!");
          return;
        }
        
        String serialNumber = serialNumberField.getText();
        if(serialNumber.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input serial number!");
            return;
        }
        
         String modelNumber = modelNumberField.getText();
        if(modelNumber.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input serial number!");
            return;
        }
        
         String city = cityField.getText();
        if(city.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input serial number!");
            return;
        }
        
        Date date = null;
        try {
            date = new SimpleDateFormat("yyyy-M-d").parse(mceDateField.getText());
        } catch (ParseException ex) {
          JOptionPane.showMessageDialog(null, "Please input correct maintenance cert expire date!");
          return;
        }
        
        // 赋值
        car.setAvailable(availableCheckbox.isSelected());
        car.setManufacturer(manu);
        car.setManufacturingTime(year);
        car.setSeats((int)seatsField.getValue());
        car.setSerialNumber(serialNumber);
        car.setModelNumber(modelNumber);
        car.setCity(city);
        car.setExpired(date);
        car.setLastUpdateTime(new Date());
        
        
        JOptionPane.showMessageDialog(null, "Successful!");
        
        if(isCreate) {
            cars.add(car);
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void mceDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mceDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mceDateFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox availableCheckbox;
    private javax.swing.JTextField cityField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> manufacturerCombobox;
    private javax.swing.JFormattedTextField manufacturerTimeField;
    private javax.swing.JFormattedTextField mceDateField;
    private javax.swing.JTextField modelNumberField;
    private javax.swing.JSpinner seatsField;
    private javax.swing.JTextField serialNumberField;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
